name:                krpc
version:             0.1.0.0
github:              "hnefatl/krpc"
license:             BSD3
author:              "Keith Collister"
maintainer:          "hnefatl@gmail.com"
copyright:           "2022 Keith Collister"

ghc-options: -Wall

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/hnefatl/krpc#readme>

dependencies:
- base >= 4.7 && < 5
- Earley == 0.13.0.1
- mtl == 2.2.2
- text == 1.2.5.0
- text-show == 3.9.6
- language-python == 0.5.8

library:
  source-dirs: src

tests:
  krpc-test:
    main: Spec.hs
    source-dirs:
    - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - krpc
    - hspec
